# Generated by Django 4.2.6 on 2023-11-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('unlimited_quantity', models.BooleanField(default=False, verbose_name='Unlimited Quantity')),
                ('hide_quantity', models.BooleanField(default=False, verbose_name='Hide Quantity')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Sold Quantity')),
                ('maximum_quantity_per_order', models.PositiveIntegerField(default=0, verbose_name='Maximum Quantity Per Order')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('require_shipping', models.BooleanField(default=False, verbose_name='Require Shipping')),
                ('cost_price', models.CharField(blank=True, max_length=255, verbose_name='Cost Price')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Weight')),
                ('weight_type', models.CharField(blank=True, max_length=255, verbose_name='Weight Type')),
                ('with_tax', models.BooleanField(default=True, verbose_name='With Tax')),
                ('url', models.URLField(verbose_name='URL')),
                ('main_image', models.URLField(verbose_name='Main Image')),
                ('short_link_code', models.CharField(blank=True, max_length=255, verbose_name='Short Link Code')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=20, verbose_name='Type')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('sort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('display_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('color', 'Color')], max_length=20, verbose_name='Display Type')),
                ('visibility', models.CharField(choices=[('always', 'Always'), ('on_condition', 'On Condition')], max_length=20, verbose_name='Visibility')),
                ('visibility_condition_type', models.CharField(blank=True, choices=[('>', '>'), ('<', '<'), ('=', '='), ('!=', '!=')], max_length=5, null=True, verbose_name='Visibility Condition Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.product', verbose_name='Product')),
                ('visibility_condition_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_condition_options', to='product.productoption', verbose_name='Visibility Condition Option')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('display_value', models.TextField(blank=True, null=True, verbose_name='Display Value')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.productoption', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Product Option Value',
                'verbose_name_plural': 'Product Option Values',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
        migrations.CreateModel(
            name='ProductRegularPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=5, verbose_name='Currency')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regular_price', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Regular Price',
                'verbose_name_plural': 'Product Regular Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=5, verbose_name='Currency')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValuePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=5, verbose_name='Currency')),
                ('product_option_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.productoptionvalue', verbose_name='Product Option Value')),
            ],
            options={
                'verbose_name': 'Product Option Value Price',
                'verbose_name_plural': 'Product Option Value Prices',
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='visibility_condition_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_condition_values', to='product.productoptionvalue', verbose_name='Visibility Condition Value'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('main', models.BooleanField(default=False, verbose_name='Main')),
                ('three_d_image_url', models.URLField(blank=True, null=True, verbose_name='3D Image URL')),
                ('alt', models.TextField(blank=True, null=True, verbose_name='Alt')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20, verbose_name='Type')),
                ('sort', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sort')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.producttag', verbose_name='Tags'),
        ),
    ]
