# Generated by Django 4.2.6 on 2023-11-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sale Price')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cost Price')),
                ('sale_end', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sale End')),
                ('unlimited_quantity', models.BooleanField(default=False, verbose_name='Unlimited Quantity')),
                ('hide_quantity', models.BooleanField(default=False, verbose_name='Hide Quantity')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Sold Quantity')),
                ('maximum_quantity_per_order', models.PositiveIntegerField(default=0, verbose_name='Maximum Quantity Per Order')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant', verbose_name='Merchant')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='product.producttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
