# Generated by Django 4.2.6 on 2023-11-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='require_shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_link_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='with_tax',
        ),
    ]
