# Generated by Django 4.2.6 on 2023-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hide_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_quantity_per_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unlimited_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='pre_tax_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='Price Currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='taxed_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
    ]
