# Generated by Django 4.2.6 on 2023-11-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_price_product_cost_price_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_price_amount',
            new_name='cost_price',
        ),
    ]
