# Generated by Django 4.2.6 on 2023-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_parent'),
        ('product', '0003_rename_cost_price_amount_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='category.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cost_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_tax_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pre_tax_price_amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='regular_price_amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='tax_amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxed_price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='taxed_price_amount'),
        ),
    ]
